//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.27 at 03:46:10 PM EDT 
//


package com.izms.pdfqurangenerator.quranmetadata;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izms.pdfqurangenerator.quranmetadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izms.pdfqurangenerator.quranmetadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Quran }
     * 
     */
    public Quran createQuran() {
        return new Quran();
    }

    /**
     * Create an instance of {@link Quran.Sajdas }
     * 
     */
    public Quran.Sajdas createQuranSajdas() {
        return new Quran.Sajdas();
    }

    /**
     * Create an instance of {@link Quran.Pages }
     * 
     */
    public Quran.Pages createQuranPages() {
        return new Quran.Pages();
    }

    /**
     * Create an instance of {@link Quran.Rukus }
     * 
     */
    public Quran.Rukus createQuranRukus() {
        return new Quran.Rukus();
    }

    /**
     * Create an instance of {@link Quran.Manzils }
     * 
     */
    public Quran.Manzils createQuranManzils() {
        return new Quran.Manzils();
    }

    /**
     * Create an instance of {@link Quran.Hizbs }
     * 
     */
    public Quran.Hizbs createQuranHizbs() {
        return new Quran.Hizbs();
    }

    /**
     * Create an instance of {@link Quran.Juzs }
     * 
     */
    public Quran.Juzs createQuranJuzs() {
        return new Quran.Juzs();
    }

    /**
     * Create an instance of {@link Quran.Suras }
     * 
     */
    public Quran.Suras createQuranSuras() {
        return new Quran.Suras();
    }

    /**
     * Create an instance of {@link Quran.Sajdas.Sajda }
     * 
     */
    public Quran.Sajdas.Sajda createQuranSajdasSajda() {
        return new Quran.Sajdas.Sajda();
    }

    /**
     * Create an instance of {@link Quran.Pages.Page }
     * 
     */
    public Quran.Pages.Page createQuranPagesPage() {
        return new Quran.Pages.Page();
    }

    /**
     * Create an instance of {@link Quran.Rukus.Ruku }
     * 
     */
    public Quran.Rukus.Ruku createQuranRukusRuku() {
        return new Quran.Rukus.Ruku();
    }

    /**
     * Create an instance of {@link Quran.Manzils.Manzil }
     * 
     */
    public Quran.Manzils.Manzil createQuranManzilsManzil() {
        return new Quran.Manzils.Manzil();
    }

    /**
     * Create an instance of {@link Quran.Hizbs.Quarter }
     * 
     */
    public Quran.Hizbs.Quarter createQuranHizbsQuarter() {
        return new Quran.Hizbs.Quarter();
    }

    /**
     * Create an instance of {@link Quran.Juzs.Juz }
     * 
     */
    public Quran.Juzs.Juz createQuranJuzsJuz() {
        return new Quran.Juzs.Juz();
    }

    /**
     * Create an instance of {@link Quran.Suras.Sura }
     * 
     */
    public Quran.Suras.Sura createQuranSurasSura() {
        return new Quran.Suras.Sura();
    }

}
