//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.27 at 03:46:10 PM EDT 
//


package com.izms.pdfqurangenerator.quranmetadata;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="suras"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sura" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="ayas" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="tname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="ename" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="rukus" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="juzs"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="juz" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="hizbs"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="quarter" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="manzils"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="manzil" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rukus"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ruku" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="pages"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="page" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sajdas"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sajda" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *                           &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="license" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "suras",
    "juzs",
    "hizbs",
    "manzils",
    "rukus",
    "pages",
    "sajdas"
})
@XmlRootElement(name = "quran")
public class Quran {

    @XmlElement(required = true)
    protected Quran.Suras suras;
    @XmlElement(required = true)
    protected Quran.Juzs juzs;
    @XmlElement(required = true)
    protected Quran.Hizbs hizbs;
    @XmlElement(required = true)
    protected Quran.Manzils manzils;
    @XmlElement(required = true)
    protected Quran.Rukus rukus;
    @XmlElement(required = true)
    protected Quran.Pages pages;
    @XmlElement(required = true)
    protected Quran.Sajdas sajdas;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "version")
    protected Float version;
    @XmlAttribute(name = "copyright")
    protected String copyright;
    @XmlAttribute(name = "license")
    protected String license;

    /**
     * Gets the value of the suras property.
     * 
     * @return
     *     possible object is
     *     {@link Quran.Suras }
     *     
     */
    public Quran.Suras getSuras() {
        return suras;
    }

    /**
     * Sets the value of the suras property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quran.Suras }
     *     
     */
    public void setSuras(Quran.Suras value) {
        this.suras = value;
    }

    /**
     * Gets the value of the juzs property.
     * 
     * @return
     *     possible object is
     *     {@link Quran.Juzs }
     *     
     */
    public Quran.Juzs getJuzs() {
        return juzs;
    }

    /**
     * Sets the value of the juzs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quran.Juzs }
     *     
     */
    public void setJuzs(Quran.Juzs value) {
        this.juzs = value;
    }

    /**
     * Gets the value of the hizbs property.
     * 
     * @return
     *     possible object is
     *     {@link Quran.Hizbs }
     *     
     */
    public Quran.Hizbs getHizbs() {
        return hizbs;
    }

    /**
     * Sets the value of the hizbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quran.Hizbs }
     *     
     */
    public void setHizbs(Quran.Hizbs value) {
        this.hizbs = value;
    }

    /**
     * Gets the value of the manzils property.
     * 
     * @return
     *     possible object is
     *     {@link Quran.Manzils }
     *     
     */
    public Quran.Manzils getManzils() {
        return manzils;
    }

    /**
     * Sets the value of the manzils property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quran.Manzils }
     *     
     */
    public void setManzils(Quran.Manzils value) {
        this.manzils = value;
    }

    /**
     * Gets the value of the rukus property.
     * 
     * @return
     *     possible object is
     *     {@link Quran.Rukus }
     *     
     */
    public Quran.Rukus getRukus() {
        return rukus;
    }

    /**
     * Sets the value of the rukus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quran.Rukus }
     *     
     */
    public void setRukus(Quran.Rukus value) {
        this.rukus = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link Quran.Pages }
     *     
     */
    public Quran.Pages getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quran.Pages }
     *     
     */
    public void setPages(Quran.Pages value) {
        this.pages = value;
    }

    /**
     * Gets the value of the sajdas property.
     * 
     * @return
     *     possible object is
     *     {@link Quran.Sajdas }
     *     
     */
    public Quran.Sajdas getSajdas() {
        return sajdas;
    }

    /**
     * Sets the value of the sajdas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quran.Sajdas }
     *     
     */
    public void setSajdas(Quran.Sajdas value) {
        this.sajdas = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(Float value) {
        this.version = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicense(String value) {
        this.license = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="quarter" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quarter"
    })
    public static class Hizbs {

        protected List<Quran.Hizbs.Quarter> quarter;
        @XmlAttribute(name = "alias")
        protected String alias;

        /**
         * Gets the value of the quarter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the quarter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuarter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quran.Hizbs.Quarter }
         * 
         * 
         */
        public List<Quran.Hizbs.Quarter> getQuarter() {
            if (quarter == null) {
                quarter = new ArrayList<Quran.Hizbs.Quarter>();
            }
            return this.quarter;
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Quarter {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "index")
            protected Short index;
            @XmlAttribute(name = "sura")
            protected Byte sura;
            @XmlAttribute(name = "aya")
            protected Short aya;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setIndex(Short value) {
                this.index = value;
            }

            /**
             * Gets the value of the sura property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSura() {
                return sura;
            }

            /**
             * Sets the value of the sura property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSura(Byte value) {
                this.sura = value;
            }

            /**
             * Gets the value of the aya property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getAya() {
                return aya;
            }

            /**
             * Sets the value of the aya property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setAya(Short value) {
                this.aya = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="juz" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "juz"
    })
    public static class Juzs {

        protected List<Quran.Juzs.Juz> juz;
        @XmlAttribute(name = "alias")
        protected String alias;

        /**
         * Gets the value of the juz property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the juz property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getJuz().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quran.Juzs.Juz }
         * 
         * 
         */
        public List<Quran.Juzs.Juz> getJuz() {
            if (juz == null) {
                juz = new ArrayList<Quran.Juzs.Juz>();
            }
            return this.juz;
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Juz {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "index")
            protected Byte index;
            @XmlAttribute(name = "sura")
            protected Byte sura;
            @XmlAttribute(name = "aya")
            protected Short aya;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setIndex(Byte value) {
                this.index = value;
            }

            /**
             * Gets the value of the sura property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSura() {
                return sura;
            }

            /**
             * Sets the value of the sura property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSura(Byte value) {
                this.sura = value;
            }

            /**
             * Gets the value of the aya property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getAya() {
                return aya;
            }

            /**
             * Sets the value of the aya property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setAya(Short value) {
                this.aya = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="manzil" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "manzil"
    })
    public static class Manzils {

        protected List<Quran.Manzils.Manzil> manzil;
        @XmlAttribute(name = "alias")
        protected String alias;

        /**
         * Gets the value of the manzil property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the manzil property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getManzil().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quran.Manzils.Manzil }
         * 
         * 
         */
        public List<Quran.Manzils.Manzil> getManzil() {
            if (manzil == null) {
                manzil = new ArrayList<Quran.Manzils.Manzil>();
            }
            return this.manzil;
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Manzil {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "index")
            protected Byte index;
            @XmlAttribute(name = "sura")
            protected Byte sura;
            @XmlAttribute(name = "aya")
            protected Byte aya;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setIndex(Byte value) {
                this.index = value;
            }

            /**
             * Gets the value of the sura property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSura() {
                return sura;
            }

            /**
             * Sets the value of the sura property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSura(Byte value) {
                this.sura = value;
            }

            /**
             * Gets the value of the aya property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getAya() {
                return aya;
            }

            /**
             * Sets the value of the aya property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setAya(Byte value) {
                this.aya = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="page" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "page"
    })
    public static class Pages {

        protected List<Quran.Pages.Page> page;

        /**
         * Gets the value of the page property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the page property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quran.Pages.Page }
         * 
         * 
         */
        public List<Quran.Pages.Page> getPage() {
            if (page == null) {
                page = new ArrayList<Quran.Pages.Page>();
            }
            return this.page;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Page {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "index")
            protected Short index;
            @XmlAttribute(name = "sura")
            protected Byte sura;
            @XmlAttribute(name = "aya")
            protected Short aya;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setIndex(Short value) {
                this.index = value;
            }

            /**
             * Gets the value of the sura property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSura() {
                return sura;
            }

            /**
             * Sets the value of the sura property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSura(Byte value) {
                this.sura = value;
            }

            /**
             * Gets the value of the aya property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getAya() {
                return aya;
            }

            /**
             * Sets the value of the aya property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setAya(Short value) {
                this.aya = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ruku" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ruku"
    })
    public static class Rukus {

        protected List<Quran.Rukus.Ruku> ruku;
        @XmlAttribute(name = "alias")
        protected String alias;

        /**
         * Gets the value of the ruku property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the ruku property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRuku().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quran.Rukus.Ruku }
         * 
         * 
         */
        public List<Quran.Rukus.Ruku> getRuku() {
            if (ruku == null) {
                ruku = new ArrayList<Quran.Rukus.Ruku>();
            }
            return this.ruku;
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Ruku {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "index")
            protected Short index;
            @XmlAttribute(name = "sura")
            protected Byte sura;
            @XmlAttribute(name = "aya")
            protected Short aya;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setIndex(Short value) {
                this.index = value;
            }

            /**
             * Gets the value of the sura property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSura() {
                return sura;
            }

            /**
             * Sets the value of the sura property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSura(Byte value) {
                this.sura = value;
            }

            /**
             * Gets the value of the aya property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getAya() {
                return aya;
            }

            /**
             * Sets the value of the aya property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setAya(Short value) {
                this.aya = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sajda" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sajda"
    })
    public static class Sajdas {

        protected List<Quran.Sajdas.Sajda> sajda;

        /**
         * Gets the value of the sajda property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the sajda property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSajda().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quran.Sajdas.Sajda }
         * 
         * 
         */
        public List<Quran.Sajdas.Sajda> getSajda() {
            if (sajda == null) {
                sajda = new ArrayList<Quran.Sajdas.Sajda>();
            }
            return this.sajda;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="sura" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="aya" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Sajda {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "index")
            protected Byte index;
            @XmlAttribute(name = "sura")
            protected Byte sura;
            @XmlAttribute(name = "aya")
            protected Short aya;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setIndex(Byte value) {
                this.index = value;
            }

            /**
             * Gets the value of the sura property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSura() {
                return sura;
            }

            /**
             * Sets the value of the sura property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSura(Byte value) {
                this.sura = value;
            }

            /**
             * Gets the value of the aya property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getAya() {
                return aya;
            }

            /**
             * Sets the value of the aya property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setAya(Short value) {
                this.aya = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sura" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="ayas" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="tname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="ename" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *                 &lt;attribute name="rukus" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sura"
    })
    public static class Suras {

        protected List<Quran.Suras.Sura> sura;
        @XmlAttribute(name = "alias")
        protected String alias;

        /**
         * Gets the value of the sura property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the sura property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSura().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quran.Suras.Sura }
         * 
         * 
         */
        public List<Quran.Suras.Sura> getSura() {
            if (sura == null) {
                sura = new ArrayList<Quran.Suras.Sura>();
            }
            return this.sura;
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="ayas" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}short" /&gt;
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="tname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="ename" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *       &lt;attribute name="rukus" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Sura {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "index")
            protected Byte index;
            @XmlAttribute(name = "ayas")
            protected Short ayas;
            @XmlAttribute(name = "start")
            protected Short start;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "tname")
            protected String tname;
            @XmlAttribute(name = "ename")
            protected String ename;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "order")
            protected Byte order;
            @XmlAttribute(name = "rukus")
            protected Byte rukus;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the index property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getIndex() {
                return index;
            }

            /**
             * Sets the value of the index property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setIndex(Byte value) {
                this.index = value;
            }

            /**
             * Gets the value of the ayas property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getAyas() {
                return ayas;
            }

            /**
             * Sets the value of the ayas property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setAyas(Short value) {
                this.ayas = value;
            }

            /**
             * Gets the value of the start property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getStart() {
                return start;
            }

            /**
             * Sets the value of the start property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setStart(Short value) {
                this.start = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the tname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTname() {
                return tname;
            }

            /**
             * Sets the value of the tname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTname(String value) {
                this.tname = value;
            }

            /**
             * Gets the value of the ename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEname() {
                return ename;
            }

            /**
             * Sets the value of the ename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEname(String value) {
                this.ename = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the order property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setOrder(Byte value) {
                this.order = value;
            }

            /**
             * Gets the value of the rukus property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getRukus() {
                return rukus;
            }

            /**
             * Sets the value of the rukus property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setRukus(Byte value) {
                this.rukus = value;
            }

        }

    }

}
